version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev
    ports:
      - "12000:12000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SERVER_URL=http://localhost:12001
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile.dev
    ports:
      - "12001:12001"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/server/node_modules
    environment:
      - NODE_ENV=development
      - PORT=12001

networks:
  default:
    name: orbmania-dev